const sneakers = [
    {
        ID: 1,
        name: "Kyrie Flytrap 6",
        brand: "Nike",
        size: [43],
        price: 161300,
        gender: "Hombre",
        sport: "Basketball",
        image: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dwab6fd02a/products/NIDM1125-800/NIDM1125-800-1.JPG",
        description: "Vestibulum sed tortor sit amet odio sodales ultricies. Etiam tincidunt, justo ut molestie consequat, sapien lacus molestie arcu, laoreet consequat nisl nisi eget est. Cras ut libero gravida, elementum nisl nec, sagittis nisl. Etiam pulvinar, nibh id pretium facilisis, odio dolor hendrerit dui, condimentum tincidunt leo ligula bibendum justo. Cras iaculis hendrerit odio, sed dapibus odio semper id. Ut condimentum eros aliquet ligula bibendum volutpat.",
    },
    {
        ID: 2,
        name: "Buzzer",
        brand: "Under Armor",
        size: [42, 43, 44],
        price: 140000,
        gender: "Hombre",
        sport: "Basketball",
        image: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dwe38210ca/products/UA3026569-101/UA3026569-101-1.JPG",
        description: "Vestibulum sed tortor sit amet odio sodales ultricies. Etiam tincidunt, justo ut molestie consequat, sapien lacus molestie arcu, laoreet consequat nisl nisi eget est. Cras ut libero gravida, elementum nisl nec, sagittis nisl. Etiam pulvinar, nibh id pretium facilisis, odio dolor hendrerit dui, condimentum tincidunt leo ligula bibendum justo. Cras iaculis hendrerit odio, sed dapibus odio semper id. Ut condimentum eros aliquet ligula bibendum volutpat.",
    },
    {
        ID: 3,
        name: "Artis II",
        brand: "Topper",
        size: [37, 38, 39, 40, 41, 42, 43, 44, 45],
        price: 88900,
        gender: "Mujer",
        sport: "Football",
        image: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dwb8ccf287/products/TO55971/TO55971-1.JPG",
        description: "Vestibulum sed tortor sit amet odio sodales ultricies. Etiam tincidunt, justo ut molestie consequat, sapien lacus molestie arcu, laoreet consequat nisl nisi eget est. Cras ut libero gravida, elementum nisl nec, sagittis nisl. Etiam pulvinar, nibh id pretium facilisis, odio dolor hendrerit dui, condimentum tincidunt leo ligula bibendum justo. Cras iaculis hendrerit odio, sed dapibus odio semper id. Ut condimentum eros aliquet ligula bibendum volutpat.",
    },
    {
        ID: 4,
        name: "Magnetico Select 2.0 Fg",
        brand: "Under Armor",
        size: [42, 44, 45],
        price: 115000,
        gender: "Hombre",
        sport: "Football",
        image: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw61dcea66/products/UA3025642-300/UA3025642-300-1.JPG",
        description: "Vestibulum sed tortor sit amet odio sodales ultricies. Etiam tincidunt, justo ut molestie consequat, sapien lacus molestie arcu, laoreet consequat nisl nisi eget est. Cras ut libero gravida, elementum nisl nec, sagittis nisl. Etiam pulvinar, nibh id pretium facilisis, odio dolor hendrerit dui, condimentum tincidunt leo ligula bibendum justo. Cras iaculis hendrerit odio, sed dapibus odio semper id. Ut condimentum eros aliquet ligula bibendum volutpat.",
    },
    {
        ID: 5,
        name: "Softride Sway",
        brand: "Puma",
        size: [34, 35],
        price: 120000,
        gender: "Mujer",
        sport: "Running",
        image: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw947e7f1c/products/PU310017-03/PU310017-03-1.JPG",
        description: "Vestibulum sed tortor sit amet odio sodales ultricies. Etiam tincidunt, justo ut molestie consequat, sapien lacus molestie arcu, laoreet consequat nisl nisi eget est. Cras ut libero gravida, elementum nisl nec, sagittis nisl. Etiam pulvinar, nibh id pretium facilisis, odio dolor hendrerit dui, condimentum tincidunt leo ligula bibendum justo. Cras iaculis hendrerit odio, sed dapibus odio semper id. Ut condimentum eros aliquet ligula bibendum volutpat.",
    },
    {
        ID: 6,
        name: "Ligra 7",
        brand: "Adidas",
        size: [39, 45],
        price: 103000,
        gender: "Unisex",
        sport: "Tennis",
        image: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dwa0d9ce84/products/AD_FZ4660/AD_FZ4660-1.JPG",
        description: "Vestibulum sed tortor sit amet odio sodales ultricies. Etiam tincidunt, justo ut molestie consequat, sapien lacus molestie arcu, laoreet consequat nisl nisi eget est. Cras ut libero gravida, elementum nisl nec, sagittis nisl. Etiam pulvinar, nibh id pretium facilisis, odio dolor hendrerit dui, condimentum tincidunt leo ligula bibendum justo. Cras iaculis hendrerit odio, sed dapibus odio semper id. Ut condimentum eros aliquet ligula bibendum volutpat.",
    },
    {
        ID: 7,
        name: "Questar",
        brand: "Adidas",
        size: [34, 35, 36, 38],
        price: 96800,
        gender: "Mujer",
        sport: "Running",
        image: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw183a74ba/products/ADHP2429/ADHP2429-1.JPG",
        description: "Vestibulum sed tortor sit amet odio sodales ultricies. Etiam tincidunt, justo ut molestie consequat, sapien lacus molestie arcu, laoreet consequat nisl nisi eget est. Cras ut libero gravida, elementum nisl nec, sagittis nisl. Etiam pulvinar, nibh id pretium facilisis, odio dolor hendrerit dui, condimentum tincidunt leo ligula bibendum justo. Cras iaculis hendrerit odio, sed dapibus odio semper id. Ut condimentum eros aliquet ligula bibendum volutpat.",
    },
    {
        ID: 8,
        name: "Zoom Vapor Cage 4 Rafa",
        brand: "Nike",
        size: [39, 41, 42, 44],
        price: 257000,
        gender: "Hombre",
        sport: "Tennis",
        image: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dwa6659107/products/NIDD1579-104/NIDD1579-104-1.JPG",
        description: "Vestibulum sed tortor sit amet odio sodales ultricies. Etiam tincidunt, justo ut molestie consequat, sapien lacus molestie arcu, laoreet consequat nisl nisi eget est. Cras ut libero gravida, elementum nisl nec, sagittis nisl. Etiam pulvinar, nibh id pretium facilisis, odio dolor hendrerit dui, condimentum tincidunt leo ligula bibendum justo. Cras iaculis hendrerit odio, sed dapibus odio semper id. Ut condimentum eros aliquet ligula bibendum volutpat.",
    },
    {
        ID: 9,
        name: "Gondor II",
        brand: "Topper",
        size: [36, 37, 38, 40, 42, 43],
        price: 87900,
        gender: "Unisex",
        sport: "Trekking",
        image: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw4f5b897d/products/TO_27132/TO_27132-1.JPG",
        description: "Vestibulum sed tortor sit amet odio sodales ultricies. Etiam tincidunt, justo ut molestie consequat, sapien lacus molestie arcu, laoreet consequat nisl nisi eget est. Cras ut libero gravida, elementum nisl nec, sagittis nisl. Etiam pulvinar, nibh id pretium facilisis, odio dolor hendrerit dui, condimentum tincidunt leo ligula bibendum justo. Cras iaculis hendrerit odio, sed dapibus odio semper id. Ut condimentum eros aliquet ligula bibendum volutpat.",
    },
    {
        ID: 10,
        name: "Terrex Soulstride",
        brand: "Adidas",
        size: [44, 45],
        price: 101500,
        gender: "Hombre",
        sport: "Trekking",
        image: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dwc12e97cd/products/ADIF5011/ADIF5011-1.JPG",
        description: "Vestibulum sed tortor sit amet odio sodales ultricies. Etiam tincidunt, justo ut molestie consequat, sapien lacus molestie arcu, laoreet consequat nisl nisi eget est. Cras ut libero gravida, elementum nisl nec, sagittis nisl. Etiam pulvinar, nibh id pretium facilisis, odio dolor hendrerit dui, condimentum tincidunt leo ligula bibendum justo. Cras iaculis hendrerit odio, sed dapibus odio semper id. Ut condimentum eros aliquet ligula bibendum volutpat.",
    },
]

module.exports = sneakers